name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          mkdir -p ~/cli/sf
          tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
          echo ~/cli/sf/bin >> $GITHUB_PATH
          PATH=~/cli/sf/bin:$PATH
          echo "$PATH" 
          sf --version
          sf plugins --core
          whereis sf
      - name: 'Populate auth file'
        shell: bash
        run: 'echo ${{secrets.SFDC_AUTH_URL}} > authFile'
      - name: Authenticate against org
        run: |
          echo "$PATH" 
          ~/cli/sf/bin/sf org login sfdx-url -f authFile
          sf org display
